### ISSUE TITLE
support multi file render in docker-compose

### ISSUE THREAD

**Issue by RelicOfTesla** [subfuzion/envtpl#10]
the docker image "scratch" not have "bash/sh", maby change alipine or busybox image?
if i will render multi file, must write a Dockerfile. not support a easy config in docker-compose , 

sample:
```yaml
image: subfuzion/envtpl
command:
      - sh # or bash
      - -c
      - |
        mkdir -p /app/gen
        envtpl /app/tmpl/aaa.conf -o /app/gen/aaa.conf
        envtpl /app/tmpl/bbb.conf -o /app/gen/ccc.conf

```
