### ISSUE TITLE
Allow to change default delimiters 

### ISSUE THREAD

**Issue by AlexShuraits** [subfuzion/envtpl#9]
Hi,

I am trying to use envtpl to render Prometheus configs.
Prometheus uses the same template engine, so the result is mixed template configurations.
Allowing to change the default delimiters for envtpl will resolve the issue.

**Comment by yurrriq** [comment]
You can use `` ` `` as follows, to handle things like Prometheus templates.

```
{{ unquoted `{{ .some.quoted.temlpate }}` }}
```

**Comment by thoratou** [comment]
+1

**Comment by subfuzion** [comment]
I haven't looked at this repo in a long time, but glad to see some people find it useful. I could expose support for replacing delimiters based on Template [Delims](https://golang.org/pkg/text/template/#Template.Delims). Before going through that effort, does @yurrriq's suggestion above solve the problem for you?

**Comment by kiefersmith** [comment]
I am also facing the same issue.

Prometheus allows for [templating in alert configurations](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/#templating).

If you want to template the alert values with envtpl you might do something like:
```yaml
# Alert for any instance that has a median request latency >1s.
  - alert: APIHighRequestLatency
    expr: api_http_request_latencies_second{quantile="0.5"} > {{ .ALERT_THRESHOLD }}
    for: 10m
    annotations:
      summary: "High request latency on {{ $labels.instance }}"
      description: "{{ $labels.instance }} has a median request latency above 1s (current value: {{ $value }}s)"
```
Where ALERT_THRESHOLD is available in the env.

I just tested wrapping `{{ $labels.instance }}` with backticks, but that did not seem to work for me.  I get a log like: `template: alerts-default.yml.tpl:34: undefined variable "$labels"`.  Might be that I am doing something wrong still.
